# Generated by Django 4.1.4 on 2023-01-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default='2000-01-01'),
        ),
    ]
