# Generated by Django 4.1.4 on 2023-01-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='lname',
            new_name='last_name',
        ),
    ]
